definitions:
  main.ErrorResponse:
    properties:
      error:
        example: true
        type: boolean
      message:
        example: Error message
        type: string
    type: object
  main.LoginRequest:
    properties:
      email:
        example: test@test.com
        type: string
      password:
        example: tester
        type: string
    required:
    - email
    - password
    type: object
  main.LoginResponse:
    properties:
      email:
        example: ""
        type: string
      error:
        example: false
        type: boolean
      message:
        example: Authentication successful
        type: string
      token:
        example: ""
        type: string
    type: object
  main.SignupRequest:
    properties:
      email:
        example: test@test.com
        type: string
      password:
        example: tester
        type: string
      username:
        example: testuser
        type: string
    required:
    - email
    - password
    - username
    type: object
  main.SignupResponse:
    properties:
      error:
        example: false
        type: boolean
      message:
        example: User created successfully
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/authenticate/login:
    post:
      description: Authenticate user with email and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
        "400":
          description: Bad Request - Invalid request body
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "401":
          description: Unauthorized - Invalid credentials
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error - JWT generation failed
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Authenticate user
      tags:
      - Authentication
  /v1/authenticate/signup:
    post:
      description: Register user with email, username, and password
      parameters:
      - description: Registration credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SignupResponse'
        "400":
          description: Bad Request - Invalid request body
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "401":
          description: Unauthorized - Failed to hash the password
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error - Failed to register user
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Register a new user
      tags:
      - Authentication
swagger: "2.0"
