GET http://localhost:8081/v1/records
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NTU2MDE0MjZ9.DIy1c9NoRTsQtdpd7RQsO_ngfyclhXBbgalo6Rt-ii8
