POST http://localhost:3000/v1/record
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NTU2NzkzNDd9.M1mzXSRLNEZ35CmvNT2nPMqul2RjYWB9oIDFpfyUQ0g

{
    "side": "buy",
    "stock_number": "2330",
    "stock_name": "台積電",
    "entry_price": 1165,
    "exit_price": 1200,
    "quantity": 1000,
    "entry_time": "2025-08-10",
    "exit_time": "2025-08-11",
    "notes": "This is a test log"
}