definitions:
  data.LogEntry:
    properties:
      created_at:
        type: string
      'id:':
        type: integer
      level:
        type: string
      message:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  main.ErrorResponse:
    properties:
      error:
        example: true
        type: boolean
      message:
        example: Error message
        type: string
    type: object
  main.ReadLogsResponse:
    properties:
      error:
        example: false
        type: boolean
      logs:
        items:
          $ref: '#/definitions/data.LogEntry'
        type: array
    type: object
  main.WriteLogRequest:
    properties:
      level:
        example: info
        type: string
      message:
        example: This is a test log message
        type: string
      name:
        example: test-service
        type: string
    required:
    - level
    - message
    - name
    type: object
  main.WriteLogResponse:
    properties:
      error:
        example: false
        type: boolean
      message:
        example: Log written successfully
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/log:
    get:
      description: Retrieve all log entries from the logging service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ReadLogsResponse'
        "500":
          description: Internal Server Error - Failed to retrieve log entries
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Read all logs
      tags:
      - Log
    post:
      description: Write a log message to the logging service
      parameters:
      - description: Log message details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.WriteLogRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.WriteLogResponse'
        "400":
          description: Bad Request - Invalid request body
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error - Failed to write log
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Write a log message
      tags:
      - Log
swagger: "2.0"
