name: Test (Container)
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: go_db
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Install dependencies
        working-directory: ./authenticate-service
        run: go mod download

      - name: Run tests
        run: go test -v ./authenticate-service/cmd/api/...
