name: Test (Container)
on:
  push:
jobs:
  test-authenticate-service:
    environment: testing
    runs-on: ubuntu-latest
    env:
      DB_NAME: go_db
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Install go dependencies
        working-directory: ./auth-service
        run: go mod download
      - name: Run tests
        working-directory: ./auth-service
        run: go test -v ./cmd/api/.